### DISCUSSION TITLE
disable __data.json in SPA mode

### DISCUSSION THREAD

**Discussion by lukaso** [sveltejs/kit#10467] [Q&A] [answered]
I'm unable to host my site in static mode because despite setting when `ssr=false` I'm still getting requests on `__data.json`.

This appears to be due to Houdini, even though I've followed these instructions: https://github.com/HoudiniGraphql/houdini/issues/85. But I'm not sure.

I could work around this by returning `{}` from a static `__data.json` except for the fact that my host, firebase, reserves `__`, and therefore blocks me providing that file. So that doesn't work.

However, my host is still rewriting `__data.json` to `index.html` (I have a `**` wildcard rewrite) because I need this for my SPA to work. https://firebase.google.com/docs/hosting/full-config

```
"hosting": {
  // ...

  // Serves index.html for requests to files or directories that do not exist
  "rewrites": [ {
    "source": "**",
    "destination": "/index.html"
  } ]
}
```

This causes the following error:

```
Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE html>" is not valid JSON
    at JSON.parse (<anonymous>)
    at start.c9bb6dea.js:3:33
```

because instead of getting a 404 or a `{}` when `data.json` is called by `sveltekit`, I'm getting the `index.html` returned and `sveltekit` doesn't handle it.

Any ideas. Many thanks!

**Comment by teemingc** [comment]
> ssr=false I'm still getting requests on __data.json

This shouldn't be happening. Can you share a minimal reproduction to help with troubleshooting this issue?

**Reply by lukaso** [reply]
OK, I've simply added this line to the standard example for houdini and `__data.json` is now called.

```
export const ssr = false
```

and changed to `adapter-static`.

Here is the repo with my changes:

https://github.com/lukaso/houdini-with-sveltekit-example

**Reply by lukaso** [reply]
When I've deployed this project to firebase with the only change being `adapter-static` and fallback, and without the `ssr=false` change, I am still faced with the `__data.json` being called.

This is the `firebase.json`:

```
{
  "hosting": [
    {
      "target": "app",
      "public": "build",
      "ignore": [
        "**/.*",
        "node_modules/**",
        "src/**",
        "static/**",
        "tests/**",
        "*.json",
        "*.js",
        "*.lock",
        "*.ts",
        "*.yaml",
        "*.md"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    }
  ]
}
```

My Github action to deploy is:

```
      - uses: FirebaseExtended/action-hosting-deploy@main
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.SERVICE_ACCOUNT_KEY }}'
          channelId: live
          projectId: hiphops-${{ env.ENV_NAME }}
          target: app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

And here is a failing preview: https://hiphops-stage--pr386-try-minimal-break-1uydybrj.web.app/

Given firebase is a commercial product, I'm not sure how to create a minimal reproducible version other than to say that something is changing things.
