### DISCUSSION TITLE
What tool is being used to minify CSS and can it be configured?

### DISCUSSION THREAD

**Discussion by cbergen** [sveltejs/kit#2771] [Q&A] [answered]
I can't see how to configure the CSS minification. To either turn it off, or to turn off specific features.

With the following CSS: 

```css
::-moz-placeholder {
	color: currentColor;
	opacity: 0.8;
}
:-ms-input-placeholder {
	color: currentColor;
	opacity: 0.8;
}
::placeholder {
	color: currentColor;
	opacity: 0.8;
}
```

The resulting minified CSS is:

```css
::-moz-placeholder,:-ms-input-placeholder,::placeholder{color:currentColor;opacity:.8}
```

This merging of rules does not work in some browsers because if the browser encounters a pseudo-element it doesn't understand, it ignores the whole block.

**Comment by benaltair** [comment]
It's my understanding that vender auto-prefixing was already included in the `build` script - if you just include the last one, it should be handled automatically with the default pre-processor configuration:
```css
::placeholder {
	color: currentColor;
	opacity: 0.8;
}
```

**Reply by benaltair** [reply]
On testing, I think this still combines selectors, but that's perhaps an issue to report to the appropriate repo if you've run into browser bugs with this configuration. For example:
```css
input.svelte-1fb4szi::-moz-placeholder,
input.svelte-1fb4szi:-ms-input-placeholder,
input.svelte-1fb4szi::placeholder {
  color: currentColor;
  opacity:.8
}
```

**Reply by cbergen** [reply]
If I stop explicitly using autoprefixer, the prefixing stops. It doesn't appear like autoprefixing is enabled by default in the sveltekit build process. But if I add those prefixed rules into the css manually, the rules are still merged.

It's just not clear to me which tool is minifying the CSS. I assume it's postcss-related - maybe cssnano - but in trying to figure this out, I'd like to know for sure.

If it is cssnano, I still don't know why it's not working. According to [this 2017 issue](https://github.com/cssnano/cssnano/issues/419), the problem with ::placeholder rule merging was eventually solved.

**Comment by cbergen** [comment]
Here's an interesting result. After adding `minify: false` to the vite.build settings, the CSS is still minified but correctly. It looks like instead of using vite to minify the CSS, this config will use postcss/cssnano instead.

The remaining issue with this is that now JS is not being minified. 

```js
// svelte.config.js
export default {
	preprocess: preprocess({
		postcss: true
	}),

	kit: {
		adapter: node({
			out: 'build',
			env: {
				port: 'PORT'
			},
		}),

		target: 'body',

		files: {
			lib: 'src'
		},

		vite: {
			build: {
				minify: false
			}
		}
	}
};
```

```js
// postcss.config.cjs
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');

module.exports = {
	plugins: [autoprefixer, cssnano]
};
```

```css
::-moz-placeholder{color:currentColor;opacity:.8}:-ms-input-placeholder{color:currentColor;opacity:.8}::placeholder{color:currentColor;opacity:.8}
```
