### DISCUSSION TITLE
dockerize sveltekit

### DISCUSSION THREAD

**Discussion by cybermedusa** [sveltejs/kit#5673] [General]
I have an issue with running sveltekit app through the docker container. I am able to run an app in docker but when I want to make some changes on frontend UI I can see them only for one second. And when I stop the container and build an image again I am able to see those changes normally. 
My Dockerfile is:
```
FROM node:16
WORKDIR /test-app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build
ENV PORT 3000
EXPOSE 3000
EXPOSE 24678 
CMD ["node", "build"]
```
My docker-compose.yml file is:
```
version: '3'
services:
  svelte-test:
    image: sveltekit-test:node
    volumes:
      - ./:/test-app/
    ports:
      - 3000:3000
      - 24678:24678
      - 5173:5173
    tty: true
    stdin_open: true
```
Port 3000 is for sveltekit, 5173 is for sveltekit but in Docker and 24678 is for vite.
And my folder structure is:
```
sveltekit-docker
    test-app
        -Dockerfile
        -docker-compose.yaml
        -package-lock.json
        -package.json
        -svelte.config.js
        -tsconfig.json
        -vite.config.js
        -all sveltekit folders (src, node_modules, static, tests)
```
And I also modified the vite.config.js file which look like this:
```
import { sveltekit } from '@sveltejs/kit/vite';
/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()],
	vite: {
		server: {
			watch: {
				usePolling: true,
			},
		},
	},
};
export default config;
```
I have no idea what is wrong so any help will be more than appreciated :)
