### DISCUSSION TITLE
`import '../app.css';`, Dark Mode, and `const ssr = false;` - `background-color` blink

### DISCUSSION THREAD

**Discussion by lukaszpolowczyk** [sveltejs/kit#6564] [Q&A] [answered]
In CSR Mode (`const ssr = false;`), the style loaded with:

```svelte
<!-- src/routes/+layout.svelte -->
<script>
  import '../app.css';
</script>
```

```css
/* src/app.css */

@media (prefers-color-scheme: dark) {
  :root {
    --color: white;
    --background-color: #333;
  }
}

@media (prefers-color-scheme: light) {
  :root {
    --color: #333;
    --background-color: white;
  }
}

html, body {
  color: var(--color);
  background-color: var(--background-color);
}
```

**Causes a blinking white background**. Even though dark mode is enabled on the system.  
When `const ssr = true;`, there is no this problem.

QUEST:  
Where is the best place to put the global style, universally? Regardless of whether SSR is enabled or disabled?

I currently place the style in `static/app.css` and load in `app.html`...

```html
<link rel="stylesheet" href="%sveltekit.assets%/app.css">.
```

...but even the Hello World example uses `import '../app.css';`, so importing styles is recommended so generally?

BETTER QUESTION:  
Are there plans or anything to make such an imported style available even before CSR starts?  

Maybe loading `src/+layout.svelte` BEFORE rendering starts, if there is no `src/+layout.js`? Or something similar?

The **most important** thing is consistent DX.
An unpleasant blink in the user's eyes when the developer fails to anticipate this CSR behavior is also something worth avoiding. It is worth designing the framework to avoid such an unpleasant experience.
