### DISCUSSION TITLE
Svelte-kit container not connecting to fastapi backend inside of a docker

### DISCUSSION THREAD

**Discussion by jkrobicki** [sveltejs/kit#7164] [Q&A]
I have an issue connecting sveltekit app to my backend in fastapi inside of the docker container. My base url is http://fastapi:8002 and it doesn't seem to respond. The endpoints work fine for other containers, same when I change base url to http://localhost:8002 from outside the docker.  Am I missing something?  Should I use reversed proxy for that or other tool like fetching the url differently?
Sveltekit Dockerfile:
```yaml
FROM node:slim AS build

COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build
CMD ["npm","run","preview"]
```
docker-compose.yaml:
```yaml
version: '3'

networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
   front:
    image: frontend:v4
    restart: always
    ports:
      - 4173:4173
    networks:
      static-network:
        ipv4_address: 172.28.1.1

  

  fastapi:
    image: fastapi:v1
    volumes:
      - ./backend/:/backend/
    command: >
      bash -c "uvicorn backend.main:app --reload --port 8002 --host 0.0.0.0"
    ports:
      - 8002:8002
    depends_on:
      - "db"
    env_file:
      - .env
    container_name: fastapi
    stdin_open: true
    tty: true
    networks:
      static-network:
        ipv4_address: 172.28.1.2
```
