### DISCUSSION TITLE
Deploy to aws amplify

### DISCUSSION THREAD

**Discussion by Hayk-Asoyan** [sveltejs/kit#9430] [Ideas]
Please tell me how to deploy the project in Amplify

**Amplify Build settings**
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**svelte.config.js**
```
import adapter from '@sveltejs/adapter-node';
import preprocess from "svelte-preprocess"

const config = {
	kit: {
		adapter: adapter(),
	},
	preprocess: preprocess()
};
```

export default config;`
