### ISSUE TITLE
Routing: Spread segments can match in the middle of another segment

### ISSUE THREAD

**Issue by rmunn** [sveltejs/kit#1049]
**Describe the bug**
Routes with `[...spread]` segments can match in the middle of another segment, without needing a `/` to match. In my repro linked below, I have a `src/routes/foo/[...rest]/index.svelte` route. This matches `/foo/one/two` as expected, with `rest` having the value `'one/two'`. But it *also* matches `/food/one/two`, with `rest` getting assigned the value `'d/one/two'`. I believe that the latter match is a bug.

The other buggy route match in my repro is the route `src/routes/[dynamic]-bar/[...rest].svelte`. This correctly matches `one-bar/two/three`, with `dynamic` being assigned `'one'` and `rest` being assigned `'two/three'`. But it *also* matches `one-bard/two/three`, with `dynamic` being assigned `'one'` and `rest` being assigned `'d/two/three'`. The latter match is, IMHO, a bug.

**Logs**
Server-side console logs produced by `pnpm run dev` and loading the four routes in my repro:
```js
{
  host: 'localhost:3000',
  path: '/foo/one/two',
  query: URLSearchParams {},
  params: { rest: 'one/two' }
}
{
  host: 'localhost:3000',
  path: '/food/one/two',
  query: URLSearchParams {},
  params: { rest: 'd/one/two' }
}
{
  host: 'localhost:3000',
  path: '/one-bar/two/three',
  query: URLSearchParams {},
  params: { dynamic: 'one', rest: 'two/three' }
}
{
  host: 'localhost:3000',
  path: '/one-bard/two/three',
  query: URLSearchParams {},
  params: { dynamic: 'one', rest: 'd/two/three' }
}
```

Browser console logs contain exactly the same info.

**To Reproduce**
Clone https://github.com/rmunn/bug-repro-svelte-kit-routing-spread-segments, run `pnpm i` then `pnpm run dev`, then open http://localhost:3000/ and follow the links to see the issue.

**Expected behavior**
The `/food/one/two` and `/one-bard/two/three` routes should have not matched; instead of matching, they should have returned a 404.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `pnpx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`

```yaml
  System:
    OS: Linux 5.4 Linux Mint 19.1 (Tessa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 9.10 GB / 62.58 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.6.3 - ~/.local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 86.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.76 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 
```

- Your browser
Firefox 86, but since this is a routing issue I expect it to repro in every browser.

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
I did not test any adapters (repro'ed in `pnpm run dev`), but I expect this would repro in the Node adapter.
</details>

**Severity**
IMHO this is of medium severity. I'd rate it high severity if I could find a way to exploit this as a security hole (e.g., if a `src/routes/log/[...rest].svelte` route could "shadow" `src/routes/login.svelte`), but since spread parameters are lower specificity the `/login` route would match before the `/log/[...rest]` route, so I can't find a way to turn this into a security exploit. Still, the potential unwanted spread-route matches when two routes share a prefix could lead to massive user confusion. E.g. if a site designer mistypes `/login` as `/loggin` on one page, a user could click on that link expecting a login page, and instead get a page that contains logs about Gin Rummy (as if the URL had been `/log/gin`, so that the `/log/[...rest]` parameter matched it).

**Additional context**
I believe this was caused by the changes made in https://github.com/sveltejs/kit/pull/768, where spread route segments were assigned a regex pattern of `'\\/?(.*)'` so that they could be made optional and `/foo/bar` could match `src/routes/foo/[...rest]/bar`. The problem is that that regex pattern is so broad that it can match in the middle of a segment (`food/bar` would assign `'d'` to `page.params.rest`), whereas I would expect a spread segment to *only* match at a `/` boundary.

This may be a duplicate of https://github.com/sveltejs/kit/issues/918, but I'm not certain that that has the same cause as this one, so just in case I'm creating this as a separate issue.
