### ISSUE TITLE
docs: copy code button removes whitespaces

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#10933]
### Describe the bug

Using the copy button in the docs returns the copied code but without the whitespaces intact. This causes the issue show below

### Reproduction

Navigate to https://kit.svelte.dev/docs/adapter-static#github-pages

Using the copy button:
```yml
name: Deploy to GitHub Pages
on:  push:    branches: 'main'
jobs:  build_site:    runs-on: ubuntu-latest    steps:      - name: Checkout        uses: actions/checkout@v3
      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`      # - name: Install pnpm      #   uses: pnpm/action-setup@v2      #   with:      #     version: 8
      - name: Install Node.js        uses: actions/setup-node@v3        with:          node-version: 18          cache: npm
      - name: Install dependencies        run: npm install
      - name: build        env:          BASE_PATH: '/${{ github.event.repository.name }}'        run: |          npm run build
      - name: Upload Artifacts        uses: actions/upload-pages-artifact@v2        with:          # this should match the `pages` option in your adapter-static options          path: 'build/'
  deploy:    needs: build_site    runs-on: ubuntu-latest
    permissions:      pages: write      id-token: write
    environment:      name: github-pages      url: ${{ steps.deployment.outputs.page_url }}
    steps:      - name: Deploy        id: deployment        uses: actions/deploy-pages@v2
```

Manually selecting and copying the text:
```yml
name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
```

### System Info

```Shell
n/a
```

### Severity

annoyance
