### ISSUE TITLE
adapter-cloudflare-workers produces broken build with kit.paths.base filled with some subpath

### ISSUE THREAD

**Issue by nosovk** [sveltejs/kit#10937]
### Describe the bug

I wan't to embed sveltekit project inside existing project (I have no access to server, that's why I stick up with CloudFlare Workers to inject my code into new routes inside existing site).
For example site.com/blog.
In svelte kit doc mentioned that there is no problem to server SvelteKit not from the root of the domain.
For that we should use kit.paths.base param.
```javascript
  kit: { adapter: adapter(),
    paths: {
    relative: false,
    base: "/blog"
    }
  },
```

This works like a charm when I use local env or `npm run preview`. Problems appears when I publish site to workers.
wrangler.toml
```toml
name = "blog"
account_id = "df3d22d535d31ae83574535632890645"
main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"
build.command = "npm run build"
compatibility_date = "2023-10-01"
workers_dev = true
routes = [
    { pattern = "b4ukraine.org/blog/*", zone_name = "b4ukraine.org" }
]
```
The config is pretty straight forward, but on workers env it broken. It seems that there are problems with router:
<img width="543" alt="image" src="https://github.com/sveltejs/kit/assets/1398808/aef50a47-05e9-4d29-a88a-d10d280c7e56">
It seems that path not matched to registered routes inside the app.

### Reproduction

setup any `base` url parameter in sveltekit config, and deploy using `@sveltejs/adapter-cloudflare-workers`

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-1370P
    Memory: 37.59 GB / 63.67 GB
  Binaries:
    Node: 20.5.1 - ~\AppData\Local\fnm_multishells\15836_1698362075353\node.EXE
    npm: 9.8.0 - ~\AppData\Local\fnm_multishells\15836_1698362075353\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\fnm_multishells\15836_1698362075353\pnpm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: ^1.1.4 => 1.1.4
    @sveltejs/kit: ^1.25.0 => 1.25.0
    svelte: ^3.59.1 => 3.59.2
    vite: ^4.4.9 => 4.4.9
```

### Severity

blocking all usage of SvelteKit
