### ISSUE TITLE
Different behavior of URLs in the CSS locally and after deployment

### ISSUE THREAD

**Issue by gressus** [sveltejs/kit#11309]
### Describe the bug

Different behavior of URLs in the CSS locally and after deployment.

Relative urls in CSS like `background-image: url('2.jpg');` works properly when a project run locally via `npm run dev`. 
But when we build a project with `npm run build` / `npm run preview` (or deploy to Vercel) the URLs in the `<style>` section cause an error:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

Because in the built project instead of trying to load the image (for example `2.jpg`) from an absolute path like '/2.jpg' it tries to load it using the following URL: 'http://localhost:4173/_app/immutable/assets/2.jpg'

```css
<section class="s1"> 
  test 1. No background image displayed in the built project.
</section>
<section class="s2"> 
  test 2
</section>
<section style="min-height: 100vh;width: 100%;background-image: url('2.jpg') !important;background-position: center;background-size: cover;position: relative;"> 
  test 3
</section>

<ul><li>No image displayed in the built project.</li></ul>

<style>
  .s1 {
    min-height: 100vh;
    width: 100%;
    background-image: url('2.jpg') !important;
    background-position: center;
    background-size: cover;
    position: relative;    
  }

  .s2 {
    min-height: 100vh;
    width: 100%;
    background-image: url('/2.jpg') !important;
    background-position: center;
    background-size: cover;
    position: relative;
  }

  li {
    list-style-image: url('favicon.png');
  }
</style>
```

### Reproduction

Repo: https://github.com/gressus/AUCAKIT2023-master
Deployed: https://aucakit-2023-master.vercel.app/

### System Info

```Shell
Chrome 120.0.6099.71
```

### Severity

annoyance
