### ISSUE TITLE
site: Copying from icon formats incorrectly 

### ISSUE THREAD

**Issue by casillasenrique** [sveltejs/kit#11916]
### Describe the bug

I've been working through SvelteKit's [GitHub Pages documentation](https://kit.svelte.dev/docs/adapter-static#github-pages) and looked to copy the `deploy.yml` file using the copy button, but when I paste the content the formatting is off which causes errors during deployment:

```yml
name: Deploy to GitHub Pages
on:  push:    branches: 'main'
jobs:  build_site:    runs-on: ubuntu-latest    steps:      - name: Checkout        uses: actions/checkout@v4
      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`      # - name: Install pnpm      #   uses: pnpm/action-setup@v3      #   with:      #     version: 8
      - name: Install Node.js        uses: actions/setup-node@v4        with:          node-version: 20          cache: npm
      - name: Install dependencies        run: npm install
      - name: build        env:          BASE_PATH: '/${{ github.event.repository.name }}'        run: |          npm run build
      - name: Upload Artifacts        uses: actions/upload-pages-artifact@v3        with:          # this should match the `pages` option in your adapter-static options          path: 'build/'
  deploy:    needs: build_site    runs-on: ubuntu-latest
    permissions:      pages: write      id-token: write
    environment:      name: github-pages      url: ${{ steps.deployment.outputs.page_url }}
    steps:      - name: Deploy        id: deployment        uses: actions/deploy-pages@v4
```

I can work around this by manually selecting the text, but just wanted to flag; this seems to happen for all other code blocks with a copy button. I also know that other people don't have this issue, so I'm thinking that this could be an Windows issue? 

### Reproduction

Use copy button on the `deploy.yml` code block under the [GitHub Pages documentation](https://kit.svelte.dev/docs/adapter-static#github-pages) and paste into a file. 

![image](https://github.com/sveltejs/kit/assets/16576314/d443481d-8312-4e91-aee2-37dbd08d8cec)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 2.38 GB / 15.79 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.26.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 122.0.6261.70
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/adapter-static: ^3.0.1 => 3.0.1 
    @sveltejs/kit: ^2.0.0 => 2.5.2 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2 
    svelte: ^4.2.7 => 4.2.12
    vite: ^5.0.3 => 5.1.4
```

### Severity

annoyance
