### ISSUE TITLE
Keyframes names scoped don't work correct in css nesting 

### ISSUE THREAD

**Issue by alkorlos** [sveltejs/kit#12364]
### Describe the bug

These two style rules should be equivalent:
```css
.box::after {
  animation: slidein 1000ms;
}
```

```css
.box {
    &::after {
      animation: slidein 1000ms;
    }
}
```

But SvelteKit handles them differently:
```css
.box.s-y_bCXRrkrYfP::after {
  animation: s-y_bCXRrkrYfP-slidein 1000ms;
}
```

```css
.box.s-y_bCXRrkrYfP {
    &::after {
      animation: slidein 1000ms;
    }
}
```

In the second case, `animation` won't work.

This is a problem only with SvelteKit, in Svelte works correctly.

### Reproduction

https://github.com/alkorlos/sveltekit-issue-bug-keyframes-nesting

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 3.04 GB / 15.85 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (126.0.2592.56)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.2
    @sveltejs/kit: ^2.0.0 => 2.5.16
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1
    svelte: ^4.2.7 => 4.2.18
    vite: ^5.0.3 => 5.3.1
```

### Severity

annoyance
