### ISSUE TITLE
Document how to cache `@sveltejs/enhanced-img` in GitHub Pages

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#13494]
### Describe the problem

i have a site build that went from 1 min on build and deploy with https://github.com/actions/deploy-pages to 11 min after adding `@sveltejs/enhanced-img`. locally, this is a 1 time cost since the transformed images are cached in `node_modules`. caching does not work out of the box in CI though. since this seems like a very common use case, i think it makes sense to recommend this to users and show them how to do it

![Image](https://github.com/user-attachments/assets/2ce1723e-d56b-43db-a3a3-8881a51dced8)

### Describe the proposed solution

https://svelte.dev/docs/kit/images seems like a good place to document how to cache `@sveltejs/enhanced-img` in GitHub actions.

another option to speed up builds would be to allow configuring which image formats to build. e.g. i only really need PNG to Avif conversion, but there's no way to configure that. related issue tracking the ability to pass `vite-imagetools` config: https://github.com/sveltejs/kit/issues/12615

### Importance

would make my life easier

**Comment by benmccann** [comment]
If you've set this up, mind sharing how you did it?

**Comment by DuCanhGH** [comment]
@janosh @benmccann I know this is a fairly old issue, but I came across this issue looking for the solution to the same problem.

Here's what I did:

```yml
jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Setup cache for imagetools
        uses: actions/cache@v5
        with:
          path: ./node_modules/.cache/imagetools
          key: ${{ runner.os }}-imagetools-${{ hashFiles('src/lib/assets/**') }}
          restore-keys: ${{ runner.os }}-imagetools-
```
I know for a fact that all my `@sveltejs/enhanced-img` assets would be in src/lib/assets, so I did `hashFiles('src/lib/assets/**')`, but I suppose you can also just do something like `hashFiles('src/**/*.{png,jpg,jpeg,webp}')`. It hardly matters anyway. Here's my build time with and without the build cache:

<img width="1711" height="137" alt="Image" src="https://github.com/user-attachments/assets/a0e928a4-b72a-4706-94f2-1880929cac55" />

<img width="1711" height="135" alt="Image" src="https://github.com/user-attachments/assets/8859e01f-2cca-428b-bc15-f917aa09d8ec" />

Around 1 minute was spent on `tinacms build` in both cases, so the uncached build was like 5 minutes, the cached build 30 seconds. Pretty great!
