### ISSUE TITLE
bug: github workflow's yaml code on adapter-static documentation page has indentation error

### ISSUE THREAD

**Issue by kkkfasya** [sveltejs/kit#13658]
### Describe the bug

the YAML code is actually correct in the docs source code [here](https://github.com/sveltejs/kit/blob/main/documentation/docs/25-build-and-deploy/50-adapter-static.md?plain=1) but it's incorrect when rendered in browser and also when being copied

tested on Chromium 134.0.6998.165
![Image](https://github.com/user-attachments/assets/cbf43097-aa39-402d-9c28-1abcfa479eca)
and Firefox 136.0.4
![Image](https://github.com/user-attachments/assets/82aabd8f-3aba-4953-945f-5b18dbd51616)

here's the code when you copy it:

```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
 node-version: 20
 cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
 BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
 npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
 # this should match the `pages` option in your adapter-static options
 path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
```

do we like YAML? do Sisyphus likes his boulder? it's the only thing that we can work with and the indentation error makes it so annoying

### Reproduction

To reproduce this, visit https://svelte.dev/docs/kit/adapter-static with firefox or chromium browser

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: Linux 6.14 Fedora Linux 40 (Workstation Edition)
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 6.91 GB / 14.94 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 20.18.2 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/bin/npm
    pnpm: 9.0.6 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 134.1.76.81
```

### Severity

annoyance
