### ISSUE TITLE
The navigation announcer's CSS could be inlined

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#1386]
**Describe the bug**
Production build generates a `start-[hash].css` file with the following content:
```css
#svelte-announcer.svelte-1j55zn5{position:absolute;left:0;top:0;clip:rect(0 0 0 0);clip-path:inset(50%);overflow:hidden;white-space:nowrap;width:1px;height:1px}
```
This file is included in built HTML, but is not required by the application.

**To Reproduce**

1. Init svelte kit skeleton
2. Build

**Expected behavior**

Only the files needed for the application should be in the resulting build.

<details>
  <summary>npmPackages</summary>
    @sveltejs/kit: next => 1.0.0-next.102 
    svelte: ^3.38.2 => 3.38.2 
</details>

**Severity**
Not a big issue, but requires an extra request to get the css, and negatievely reflects framework tidiness. 

**Other questions**
Is there some unused javascript shipped with the bundle?
