### ISSUE TITLE
SvelteKit with Node Adapter Not Reading x-forwarded-for Header as Client IP

### ISSUE THREAD

**Issue by tsegreto** [sveltejs/kit#13887]
### Describe the bug

When using SvelteKit with the Node adapter behind a Traefik reverse proxy, the `getClientAddress()` function returns the internal Docker network IP instead of the actual client IP from the `x-forwarded-for` header, despite proper configuration of proxy trust settings.

## Expected Behavior

`getClientAddress()` should return the real client IP address from the `x-forwarded-for` header when properly configured with `trustProxy: true` and appropriate environment variables.

## Actual Behavior

- `getClientAddress()` returns: `192.192.168.97.1` (internal Docker network IP)
- `x-forwarded-for` header contains: `127.0.0.1`
- `x-real-ip` header contains: `127.0.0.1`

The function appears to be ignoring the forwarded headers and falling back to the direct connection IP.

### docker-compose.yml
```yaml
traefik:
    image: traefik:latest
    container_name: traefik
    network_mode: host
    command:
        - --log.level=INFO
        - --api.dashboard=true
        - --api.insecure=true
        - --providers.docker=true
        - --providers.docker.exposedbydefault=false
        - --entrypoints.web.address=:80
        - --entrypoints.web.forwardedHeaders.insecure=true
        - --entrypoints.websecure.address=:443
        - --entrypoints.websecure.forwardedHeaders.insecure=true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro

sveltekit:
    build:
        context: sveltekit
        dockerfile: ./Dockerfile
    container_name: sveltekit
    networks:
        - app-network
    labels:
        - traefik.enable=true
        - traefik.http.routers.sveltekit.rule=Host(`sveltekit`)
        - traefik.http.routers.sveltekit.entrypoints=web
        - traefik.http.services.sveltekit.loadbalancer.server.port=5173
    environment:
        - NODE_ENV=development
        - ADDRESS_HEADER=x-forwarded-for
        - PROTOCOL_HEADER=x-forwarded-proto
        - HOST_HEADER=x-forwarded-host
        - PORT_HEADER=x-forwarded-port
        - XFF_DEPTH=1
```

### svelte.config.js
```javascript
import adapter from "@sveltejs/adapter-node";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

const config = {
    preprocess: vitePreprocess(),
    kit: {
        adapter: adapter({
            trustProxy: true,
        }),
    },
};

export default config;
```

### Dockerfile
```dockerfile
FROM node:22-alpine
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY ./ .
EXPOSE 5173
EXPOSE 24678
ENV NODE_ENV=development
ENV ADDRESS_HEADER=x-forwarded-for
ENV XFF_DEPTH=1
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
```

### Test Code
```javascript
// In a server-side handler
const ipAddress = getClientAddress(); // Returns: 192.192.168.97.1
const xForwardedFor = request.headers.get("x-forwarded-for"); // Returns: 127.0.0.1
const xRealIp = request.headers.get("x-real-ip"); // Returns: 127.0.0.1
```

## Steps to Reproduce

1. Set up SvelteKit with Node adapter behind Traefik reverse proxy
2. Configure Traefik with `forwardedHeaders.insecure=true`
3. Configure SvelteKit adapter with `trustProxy: true`
4. Set environment variables: `ADDRESS_HEADER=x-forwarded-for`, `XFF_DEPTH=1`
5. Call `getClientAddress()` in a server-side handler
6. Observe that it returns internal network IP instead of forwarded IP

### Logs

```Shell

```

### System Info

```Shell
- SvelteKit Version**: 2.16.0
- Node Adapter Version**: 5.2.12
- Node.js Version**: 22
- Operating System**: Docker (Alpine Linux)
- Reverse Proxy**: Traefik (latest)
```

### Severity

annoyance

### Additional Information

The headers are being properly set by Traefik as evidenced by being able to read them directly from `request.headers.get()`. However, `getClientAddress()` is not respecting these headers despite the adapter being configured with `trustProxy: true` and the appropriate environment variables being set.
