### ISSUE TITLE
Add initial docker files for development and production evironments

### ISSUE THREAD

**Issue by koodeau** [sveltejs/kit#3995]
### Describe the problem

It's nice to keep dev process organized inside docker container for many people working on Sveltekit projects, and one more for deployment with node adapter.

### Describe the proposed solution

# For development:

but recently vite's hmr stopped working for some reason

`Dockerfile.dev`

```Dockerfile
FROM node:14-alpine

ENV NODE_ENV development

WORKDIR /app

COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "yarn.lock", "./"]

RUN yarn

COPY . .

EXPOSE 3000
EXPOSE 24678

CMD ["yarn", "dev", "--host", "0.0.0.0"]
``` 

`docker-compose.dev.yml`

```yml
version: '3.9'
services:
  dev:
    image: dev
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - /app
      - /app/node_modules
```

# For production:

`Dockerfile`

```Dockerfile
FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

RUN yarn

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["build/index.js"]
```

`docker-compose.yml`

```yml
version: '3.9'
services:
  web:
    image: web
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app
      - /app/node_modules
```

# Usage

```bash
# for dev
docker-compose -f docker-compose.dev.yml up --build

# for production
docker-compose -f docker-compose.yml up --build
```

### Importance

would make my life easier

### Additional Information

I works great for production, but has some issues with HMR in development, but it works an finding such solution in the internet could take a lot of time. So it would be great if you include it in templates that created with `npm init svelte@next my-app`
