### ISSUE TITLE
Changing the preview port in `svelte.config.js` doesn't work

### ISSUE THREAD

**Issue by NatoBoram** [sveltejs/kit#5097]
### Describe the bug

I want to change the `preview` port like this:

```typescript
import adapter from '@sveltejs/adapter-static';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),
	kit: {
		adapter: adapter(),
		prerender: {
			default: true
		},
		vite: () => ({
			server: { port: 3001 },
			preview: { port: 3002 } // Definitely not 3000
		})
	}
};

export default config;
```

It works for `server` but not for `preview`.

It works in Vite and I'm glad your issue template is so similar, because I could copy everything when I realized it worked there halfway.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-icbq3v?file=svelte.config.js&view=editor

1. Look at the dev server port, it's now `:3001`.
2. <kbd>CTRL</kbd>+<kbd>C</kbd> and launch the preview with `npm run build && npm run preview`
3. Look at the preview port, it's now `:3000`. However, the config has `:3002` in it.

### Logs

```shell
> svelte-kit preview


  SvelteKit v1.0.0-next.345

  local:   http://localhost:3000
  network: not exposed
  network: not exposed

  Use --host to expose server to other devices on this network
```

### System Info

```yaml
System:
    OS: Linux 5.17 Pop!_OS 22.04 LTS
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    Memory: 10.84 GB / 23.42 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.2.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.9.0 - /usr/bin/npm
  Browsers:
    Chrome: 101.0.4951.41
    Firefox: 100.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.48 
    @sveltejs/adapter-static: next => 1.0.0-next.32 
    @sveltejs/kit: next => 1.0.0-next.345 
    svelte: ^3.48.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

Workaround in `playwright.config.ts`:

```typescript
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
	webServer: {
		command: 'pnpm run build && pnpm run preview --port 3002',
		port: 3002
	}
};

export default config;
```

You also need to change it in `package.json`, but then you wouldn't be able to use environment variables if you wanted to.

In the issue template, you should change the language to `yaml` in *System Info* :)
