### ISSUE TITLE
Cloudflare Workers | `server.init is not a function`

### ISSUE THREAD

**Issue by EstebanBorai** [sveltejs/kit#5736]
### Describe the bug

Using the `@sveltejs/adapter-cloudflare-workers` at version `1.0.0-next.52` adapter Im publishing a SvelteKit page to Cloudflare Workers using the Cloudflare Worker Action as follows:

<details>
   <summary>Deployment Action</summary>

```yml
name: Publish
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci

      - name: Builds for Production
        env:
          NODE_ENV: "production"
        run: npm run build

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKERS }}
          wranglerVersion: '2.0.23'
```
</details>

The deployment process works as expected, but whenever I try to visit my page i get a worker exception.
Running the realtime logger I get the following object in the exceptions array:

```json
{
      "name": "TypeError",
      "message": "server.init is not a function",
      "timestamp": 1658968502284
}
```

I can see the call to `server.init` in the `worker.js` file from the output on `.svelte-kit` whenever I run: `NODE_ENV=production npm run build`.

```js
// .svelte-kit/cloudflare-workers-tmp/entry.js
var import_kv_asset_handler = __toESM(require_dist());
import static_asset_manifest_json from "__STATIC_CONTENT_MANIFEST";
var static_asset_manifest = JSON.parse(static_asset_manifest_json);
var server = new Server(manifest);
var prefix = `/${manifest.appDir}/`;
var entry_default = {
  async fetch(req, env, context) {
    server.init({ env });
    const url = new URL(req.url);
    if (url.pathname.startsWith(prefix)) {
      const res = await get_asset_from_kv(req, env, context);
      if (is_error(res.status))
        return res;
      const cache_control = url.pathname.startsWith(prefix + "immutable/") ? "public, immutable, max-age=31536000" : "no-cache";
      return new Response(res.body, {
        headers: {
          "cache-control": cache_control,
          "content-type": res.headers.get("content-type"),
          "x-robots-tag": "noindex"
        }
      });
    }
```

Checking in the output from the same file, I can see the `Server` class definition.
But the `init` method is missing:

<details>
  <summary>worker.js Server class definition</summary>

```js
var Server = class {
  constructor(manifest2) {
    this.options = {
      csp: { "mode": "auto", "directives": { "upgrade-insecure-requests": false, "block-all-mixed-content": false } },
      dev: false,
      floc: false,
      get_stack: (error2) => String(error2),
      handle_error: (error2, event) => {
        this.options.hooks.handleError({
          error: error2,
          event,
          get request() {
            throw new Error("request in handleError has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details");
          }
        });
        error2.stack = this.options.get_stack(error2);
      },
      hooks: null,
      hydrate: true,
      manifest: manifest2,
      method_override: { "parameter": "_method", "allowed": [] },
      paths: { base, assets },
      prefix: assets + "/_app/immutable/",
      prerender: {
        default: false,
        enabled: true
      },
      read,
      root: Root,
      service_worker: base + "/service-worker.js",
      router: true,
      template,
      template_contains_nonce: false,
      trailing_slash: "never"
    };
  }
  async respond(request, options = {}) {
    if (!(request instanceof Request)) {
      throw new Error("The first argument to server.respond must be a Request object. See https://github.com/sveltejs/kit/pull/3384 for details");
    }
    if (!this.options.hooks) {
      const module = await Promise.resolve().then(() => (init_hooks_35d24a4b(), hooks_35d24a4b_exports));
      this.options.hooks = {
        getSession: module.getSession || (() => ({})),
        handle: module.handle || (({ event, resolve: resolve2 }) => resolve2(event)),
        handleError: module.handleError || (({ error: error2 }) => console.error(error2.stack)),
        externalFetch: module.externalFetch || fetch
      };
    }
    return respond(request, this.options, options);
  }
};
```
</details>

### Reproduction

1. Create a SvelteKit Project
2. Install the `@sveltejs/adapter-cloudflare-workers` on version `^1.0.0-next.52`
3. Publish to Cloudflare Workers
4. Visit the workers instance

### Logs

```shell
{
      "name": "TypeError",
      "message": "server.init is not a function",
      "timestamp": 1658968502284
}
```

### System Info

```shell
@sveltejs/adapter-cloudflare-workers: ^1.0.0-next.52
@sveltejs/kit: 1.0.0-next.354
svelte: ^3.44.0
```

### Severity

annoyance
