### ISSUE TITLE
[DOCS] webkit scrollbar styling

### ISSUE THREAD

**Issue by david-plugge** [sveltejs/kit#7901]
### Describe the problem

I really like the new look of the docs, even more so the added dark mode!

However in chrome the scrollbars really stand out as they are a lot brighter than the background.

![image](https://user-images.githubusercontent.com/59972093/205130975-3d0a95f3-dc89-4d9e-8410-335904bb1664.png)

### Describe the proposed solution

Add some Styles to make the scrollbars less _flashy_ 

```css
::-webkit-scrollbar {
	width: 8px;
	height: 8px;
}
::-webkit-scrollbar-corner {
	background-color: transparent;
}
::-webkit-scrollbar-thumb {
	background-color: var(--sk-scrollbar);
}
::-webkit-scrollbar-track {
	background-color: transparent;
}
```

With the styles applied:

![image](https://user-images.githubusercontent.com/59972093/205133496-81ebfd93-e8a7-4339-9ccc-7f66e483aa01.png)

### Alternatives considered

Keep it as is

### Importance

nice to have
