### ISSUE TITLE
[Docker/SvelteKit] Cross-site post form submissions are forbidden

### ISSUE THREAD

**Issue by Bishwas-py** [sveltejs/kit#9582]
### Describe the bug

I was working with SvelteKit and I got an issue of cross-site post from submission are forbidden,  I was setting up SvelteKit with Django along with Docker.  Below is my code for `Dockerfile`

```
# frontend_aiweb_storm/Dockerfile

# Use the official Node.js image as the base image
FROM node:18.1.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN if [ "$PRODUCTION" = "true" ]; then \
    npm ci --production; \
else \
    npm ci; \
fi

# Copy the rest of the application code
COPY . .

RUN if [ "$PRODUCTION" = "true" ]; then \
    npm run build; \
fi

CMD if [ "$PRODUCTION" = "true" ]; then \
    ORIGIN=$ORIGIN PORT=$PORT VITE_PUBLIC_BASE_SOURCE=$PUBLIC_BASE_SOURCE VITE_PUBLIC_WEBSOCKET_SCHEME=$PUBLIC_WEBSOCKET_SCHEME VITE_SECRET_BASE_URL=$SECRET_BASE_URL node build/index.js; \
else \
    VITE_PUBLIC_BASE_SOURCE=$PUBLIC_BASE_SOURCE VITE_PUBLIC_WEBSOCKET_SCHEME=$PUBLIC_WEBSOCKET_SCHEME VITE_SECRET_BASE_URL=$SECRET_BASE_URL ORIGIN=http://localhost:3000 npm run dev; \
fi
```
I have also passed the ORIGIN, but I don't know why is it not working.

And below is the `docker-compose.yml`:

```yaml
version: '3.9'

services:
  frontend:
    build: frontend_aiweb_storm
    ports:
      - ':3000'
    depends_on:
      - backend
    environment:
      - ORIGIN=http://localhost:3000
      - PRODUCTION=false
      - PORT=3000
      - PUBLIC_BASE_URL=http://backend:8000
      - PUBLIC_BASE_SOURCE=backend:8000
      - PUBLIC_WEBSOCKET_SCHEME=ws://
      - SECRET_BASE_URL=http://backend:8000
      - SECRET_BASE_SOURCE=backend:8000

    env_file:
      - frontend_aiweb_storm/.env

    volumes:
      - ./frontend_aiweb_storm:/app

  backend:
    build: backend_aiweb_storm
    ports:
      - '8000:8000'
    environment:
          - ALLOWED_HOSTS=backend,localhost,127.0.0.1
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '3000:80'
    depends_on:
      - frontend
      - backend
```

How can I fix the issue of origin. It works perfectly fine when the done via build, i.e. PRODUCTION is true. But in `npm run dev` [i.e. PRODUCTION is false], the site works smooth but form submission are not allowed.

### Reproduction

1. Create a SvelteKit project
2. Assign port 3000 of sveltekit with exposed 3000 port via NGINX. 
3. Make sure if 
4. Run `docker-compose up` to start the containers.
5. Open the browser and navigate to `http://localhost:3000`.
6. Submit the form on the page.
7. Observe the "cross-site POST from submission are forbidden" error in the browser console.

### System Info

```Shell
System:
    OS: Linux 6.2 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 2.31 GB / 9.58 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.1.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.1.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/adapter-node: ^1.1.6 => 1.1.6 
    @sveltejs/kit: ^1.2.9 => 1.8.3 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Here's the `package.json`

```json
{
	"name": "frontend-web",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev --port 3000 --host 0.0.0.0",
		"build": "vite build",
		"preview": "vite preview --port 3000",
		"start": "PORT=3011 node ./build/index.js",
		"fake_start": "vite dev --host 0 --port 3011",
		"test": "playwright test",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"test:unit": "vitest",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@fortawesome/free-brands-svg-icons": "^6.2.1",
		"@fortawesome/free-solid-svg-icons": "^6.2.1",
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^1.0.0",
		"@sveltejs/kit": "^1.2.9",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"autoprefixer": "^10.4.7",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.14",
		"postcss-load-config": "^4.0.1",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"svelte-fa": "^3.0.3",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.1.5",
		"tslib": "^2.4.1",
		"typescript": "^4.9.3",
		"vite": "^4.0.0",
		"vitest": "^0.25.3"
	},
	"type": "module",
	"dependencies": {
		"@sveltejs/adapter-node": "^1.1.6",
		"@tiptap/core": "^2.0.1",
		"@tiptap/pm": "^2.0.1",
		"@tiptap/starter-kit": "^2.0.1",
		"@types/showdown": "^2.0.0",
		"moment": "^2.29.4",
		"showdown": "^2.1.0"
	}
}
```
